version: '3.8'

services:
  app:
    build:
      context: .
      args:
        VERSION: ${VERSION:-dev}
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app/app  # Hot reload для разработки
    command: python -m app.app