# categories.py
CATEGORIES = {
    "clothing": "Одежда и обувь",
    "entertainment": "Отдых и развлечения",
    "cookies": "Печенье (конфеты и другое сладкое)",
    "pixel": "Пиксель",
    "gifts": "Подарки",
    "electronics": "Покупка эл.техники, мебели",
    "travel": "Путешествие",
    "baby_puree": "Пюре, йогурт детям",
    "work_food": "Работа_еда",
    "misc": "Разное",
    "sonya_expenses": "Расходы Соня",
    "polina_expenses": "Расходы_Полина",
    "repair": "Ремонт (техники, обуви, одежды, квартира)",
    "restaurant": "Ресторан, кафе",
    "fish": "Рыба",
    "kindergarten": "Садик",
    "mobile": "Сотовая связь",
    "dancing": "Танцы",
    "transport": "Транспорт",
    "fruits": "Фрукты",
    "bread": "Хлеб (батон)",
    "household": "Хоз_средства",
    "polina_school": "Школа_Полина",
    "school_food": "Школа_питание",
    "aleksandrovskaya": "Александровская",
    "vara_expenses": "Варе на расходы",
    "vara_business": "Варин_бизнес_хотелки",
    "ham": "Ветчина (колбаса, сосиски)",
    "kids_treats": "Вкусности детям",
    "canal_entry": "Въезд через канаву",
    "garbage": "Вывоз мусора",
    "debts": "Долги",
    "food": "Еда",
    "dinner_party": "Званый ужин",
    "intim": "Интим",
    "utilities": "Коммунальные_платежи",
    "cosmetics": "Косметика и т.д",
    "cat_expenses": "Кошачьи расходы",
    "groats": "Крупы, макароны",
    "medicine": "Лекарства и лечения",
    "lenta": "Лента",
    "dairy": "Молочка (молоко, кефир, творог)",
    "meat": "Мясо (кура, гов, свинина, индейка)",
    "vegetables": "Овощи"
}
